/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/liangrog/kube-crd-example/pkg/apis/foo/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ClusterHelloTypeLister helps list ClusterHelloTypes.
type ClusterHelloTypeLister interface {
	// List lists all ClusterHelloTypes in the indexer.
	List(selector labels.Selector) (ret []*v1.ClusterHelloType, err error)
	// Get retrieves the ClusterHelloType from the index for a given name.
	Get(name string) (*v1.ClusterHelloType, error)
	ClusterHelloTypeListerExpansion
}

// clusterHelloTypeLister implements the ClusterHelloTypeLister interface.
type clusterHelloTypeLister struct {
	indexer cache.Indexer
}

// NewClusterHelloTypeLister returns a new ClusterHelloTypeLister.
func NewClusterHelloTypeLister(indexer cache.Indexer) ClusterHelloTypeLister {
	return &clusterHelloTypeLister{indexer: indexer}
}

// List lists all ClusterHelloTypes in the indexer.
func (s *clusterHelloTypeLister) List(selector labels.Selector) (ret []*v1.ClusterHelloType, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ClusterHelloType))
	})
	return ret, err
}

// Get retrieves the ClusterHelloType from the index for a given name.
func (s *clusterHelloTypeLister) Get(name string) (*v1.ClusterHelloType, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("clusterhellotype"), name)
	}
	return obj.(*v1.ClusterHelloType), nil
}
