/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/liangrog/kube-crd-example/pkg/apis/foo/v1"
	scheme "github.com/liangrog/kube-crd-example/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	autoscaling "k8s.io/kubernetes/pkg/apis/autoscaling"
)

// ClusterHelloTypesGetter has a method to return a ClusterHelloTypeInterface.
// A group's client should implement this interface.
type ClusterHelloTypesGetter interface {
	ClusterHelloTypes() ClusterHelloTypeInterface
}

// ClusterHelloTypeInterface has methods to work with ClusterHelloType resources.
type ClusterHelloTypeInterface interface {
	Create(*v1.ClusterHelloType) (*v1.ClusterHelloType, error)
	Update(*v1.ClusterHelloType) (*v1.ClusterHelloType, error)
	UpdateStatus(*v1.ClusterHelloType) (*v1.ClusterHelloType, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.ClusterHelloType, error)
	List(opts metav1.ListOptions) (*v1.ClusterHelloTypeList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ClusterHelloType, err error)
	GetScale(clusterHelloTypeName string, options metav1.GetOptions) (*autoscaling.Scale, error)
	UpdateScale(clusterHelloTypeName string, scale *autoscaling.Scale) (*autoscaling.Scale, error)

	ClusterHelloTypeExpansion
}

// clusterHelloTypes implements ClusterHelloTypeInterface
type clusterHelloTypes struct {
	client rest.Interface
}

// newClusterHelloTypes returns a ClusterHelloTypes
func newClusterHelloTypes(c *ExampleV1Client) *clusterHelloTypes {
	return &clusterHelloTypes{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterHelloType, and returns the corresponding clusterHelloType object, and an error if there is any.
func (c *clusterHelloTypes) Get(name string, options metav1.GetOptions) (result *v1.ClusterHelloType, err error) {
	result = &v1.ClusterHelloType{}
	err = c.client.Get().
		Resource("clusterhellotypes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterHelloTypes that match those selectors.
func (c *clusterHelloTypes) List(opts metav1.ListOptions) (result *v1.ClusterHelloTypeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ClusterHelloTypeList{}
	err = c.client.Get().
		Resource("clusterhellotypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterHelloTypes.
func (c *clusterHelloTypes) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("clusterhellotypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a clusterHelloType and creates it.  Returns the server's representation of the clusterHelloType, and an error, if there is any.
func (c *clusterHelloTypes) Create(clusterHelloType *v1.ClusterHelloType) (result *v1.ClusterHelloType, err error) {
	result = &v1.ClusterHelloType{}
	err = c.client.Post().
		Resource("clusterhellotypes").
		Body(clusterHelloType).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterHelloType and updates it. Returns the server's representation of the clusterHelloType, and an error, if there is any.
func (c *clusterHelloTypes) Update(clusterHelloType *v1.ClusterHelloType) (result *v1.ClusterHelloType, err error) {
	result = &v1.ClusterHelloType{}
	err = c.client.Put().
		Resource("clusterhellotypes").
		Name(clusterHelloType.Name).
		Body(clusterHelloType).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *clusterHelloTypes) UpdateStatus(clusterHelloType *v1.ClusterHelloType) (result *v1.ClusterHelloType, err error) {
	result = &v1.ClusterHelloType{}
	err = c.client.Put().
		Resource("clusterhellotypes").
		Name(clusterHelloType.Name).
		SubResource("status").
		Body(clusterHelloType).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterHelloType and deletes it. Returns an error if one occurs.
func (c *clusterHelloTypes) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clusterhellotypes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterHelloTypes) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("clusterhellotypes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterHelloType.
func (c *clusterHelloTypes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ClusterHelloType, err error) {
	result = &v1.ClusterHelloType{}
	err = c.client.Patch(pt).
		Resource("clusterhellotypes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}

// GetScale takes name of the clusterHelloType, and returns the corresponding autoscaling.Scale object, and an error if there is any.
func (c *clusterHelloTypes) GetScale(clusterHelloTypeName string, options metav1.GetOptions) (result *autoscaling.Scale, err error) {
	result = &autoscaling.Scale{}
	err = c.client.Get().
		Resource("clusterhellotypes").
		Name(clusterHelloTypeName).
		SubResource("scale").
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// UpdateScale takes the top resource name and the representation of a scale and updates it. Returns the server's representation of the scale, and an error, if there is any.
func (c *clusterHelloTypes) UpdateScale(clusterHelloTypeName string, scale *autoscaling.Scale) (result *autoscaling.Scale, err error) {
	result = &autoscaling.Scale{}
	err = c.client.Put().
		Resource("clusterhellotypes").
		Name(clusterHelloTypeName).
		SubResource("scale").
		Body(scale).
		Do().
		Into(result)
	return
}
