/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	foov1 "github.com/liangrog/kube-crd-example/pkg/apis/foo/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	autoscaling "k8s.io/kubernetes/pkg/apis/autoscaling"
)

// FakeClusterHelloTypes implements ClusterHelloTypeInterface
type FakeClusterHelloTypes struct {
	Fake *FakeExampleV1
}

var clusterhellotypesResource = schema.GroupVersionResource{Group: "example.com", Version: "v1", Resource: "clusterhellotypes"}

var clusterhellotypesKind = schema.GroupVersionKind{Group: "example.com", Version: "v1", Kind: "ClusterHelloType"}

// Get takes name of the clusterHelloType, and returns the corresponding clusterHelloType object, and an error if there is any.
func (c *FakeClusterHelloTypes) Get(name string, options v1.GetOptions) (result *foov1.ClusterHelloType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterhellotypesResource, name), &foov1.ClusterHelloType{})
	if obj == nil {
		return nil, err
	}
	return obj.(*foov1.ClusterHelloType), err
}

// List takes label and field selectors, and returns the list of ClusterHelloTypes that match those selectors.
func (c *FakeClusterHelloTypes) List(opts v1.ListOptions) (result *foov1.ClusterHelloTypeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterhellotypesResource, clusterhellotypesKind, opts), &foov1.ClusterHelloTypeList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &foov1.ClusterHelloTypeList{ListMeta: obj.(*foov1.ClusterHelloTypeList).ListMeta}
	for _, item := range obj.(*foov1.ClusterHelloTypeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterHelloTypes.
func (c *FakeClusterHelloTypes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterhellotypesResource, opts))
}

// Create takes the representation of a clusterHelloType and creates it.  Returns the server's representation of the clusterHelloType, and an error, if there is any.
func (c *FakeClusterHelloTypes) Create(clusterHelloType *foov1.ClusterHelloType) (result *foov1.ClusterHelloType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterhellotypesResource, clusterHelloType), &foov1.ClusterHelloType{})
	if obj == nil {
		return nil, err
	}
	return obj.(*foov1.ClusterHelloType), err
}

// Update takes the representation of a clusterHelloType and updates it. Returns the server's representation of the clusterHelloType, and an error, if there is any.
func (c *FakeClusterHelloTypes) Update(clusterHelloType *foov1.ClusterHelloType) (result *foov1.ClusterHelloType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterhellotypesResource, clusterHelloType), &foov1.ClusterHelloType{})
	if obj == nil {
		return nil, err
	}
	return obj.(*foov1.ClusterHelloType), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterHelloTypes) UpdateStatus(clusterHelloType *foov1.ClusterHelloType) (*foov1.ClusterHelloType, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterhellotypesResource, "status", clusterHelloType), &foov1.ClusterHelloType{})
	if obj == nil {
		return nil, err
	}
	return obj.(*foov1.ClusterHelloType), err
}

// Delete takes name of the clusterHelloType and deletes it. Returns an error if one occurs.
func (c *FakeClusterHelloTypes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(clusterhellotypesResource, name), &foov1.ClusterHelloType{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterHelloTypes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterhellotypesResource, listOptions)

	_, err := c.Fake.Invokes(action, &foov1.ClusterHelloTypeList{})
	return err
}

// Patch applies the patch and returns the patched clusterHelloType.
func (c *FakeClusterHelloTypes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *foov1.ClusterHelloType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterhellotypesResource, name, pt, data, subresources...), &foov1.ClusterHelloType{})
	if obj == nil {
		return nil, err
	}
	return obj.(*foov1.ClusterHelloType), err
}

// GetScale takes name of the clusterHelloType, and returns the corresponding scale object, and an error if there is any.
func (c *FakeClusterHelloTypes) GetScale(clusterHelloTypeName string, options v1.GetOptions) (result *autoscaling.Scale, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetSubresourceAction(clusterhellotypesResource, "scale", clusterHelloTypeName), &autoscaling.Scale{})
	if obj == nil {
		return nil, err
	}
	return obj.(*autoscaling.Scale), err
}

// UpdateScale takes the representation of a scale and updates it. Returns the server's representation of the scale, and an error, if there is any.
func (c *FakeClusterHelloTypes) UpdateScale(clusterHelloTypeName string, scale *autoscaling.Scale) (result *autoscaling.Scale, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterhellotypesResource, "scale", scale), &autoscaling.Scale{})
	if obj == nil {
		return nil, err
	}
	return obj.(*autoscaling.Scale), err
}
